//@version=5
indicator("Moving Average Ribbons", shorttitle="MA Ribbons", overlay=true, timeframe="", timeframe_gaps=true)

ma(source, length, type) =>
    type == "SMA" ? ta.sma(source, length) :
     type == "EMA" ? ta.ema(source, length) :
     type == "SMMA (RMA)" ? ta.rma(source, length) :
     type == "WMA" ? ta.wma(source, length) :
     type == "VWMA" ? ta.vwma(source, length) :
     na

show_ma1   = input(true   , "MA №1", inline="MA #1")
ma1_type   = input.string("EMA"  , ""     , inline="MA #1", options=["SMA", "EMA", "SMMA (RMA)", "WMA", "VWMA"])
ma1_source = input(close  , ""     , inline="MA #1")
ma1_length = input.int(5     , ""     , inline="MA #1", minval=1)

show_ma2   = input(true   , "MA №2", inline="MA #2")
ma2_type   = input.string("EMA"  , ""     , inline="MA #2", options=["SMA", "EMA", "SMMA (RMA)", "WMA", "VWMA"])
ma2_source = input(close  , ""     , inline="MA #2")
ma2_length = input.int(10     , ""     , inline="MA #2", minval=1)

show_ma3   = input(true   , "MA №3", inline="MA #3")
ma3_type   = input.string("EMA"  , ""     , inline="MA #3", options=["SMA", "EMA", "SMMA (RMA)", "WMA", "VWMA"])
ma3_source = input(close  , ""     , inline="MA #3")
ma3_length = input.int(15    , ""     , inline="MA #3", minval=1)

show_ma4   = input(true   , "MA №4", inline="MA #4")
ma4_type   = input.string("EMA"  , ""     , inline="MA #4", options=["SMA", "EMA", "SMMA (RMA)", "WMA", "VWMA"])
ma4_source = input(close  , ""     , inline="MA #4")
ma4_length = input.int(20    , ""     , inline="MA #4", minval=1)

show_ma5   = input(true   , "MA №5", inline="MA #5")
ma5_type   = input.string("EMA"  , ""     , inline="MA #5", options=["SMA", "EMA", "SMMA (RMA)", "WMA", "VWMA"])
ma5_source = input(close  , ""     , inline="MA #5")
ma5_length = input.int(25    , ""     , inline="MA #5", minval=1)

show_ma6   = input(true   , "MA №6", inline="MA #6")
ma6_type   = input.string("EMA"  , ""     , inline="MA #6", options=["SMA", "EMA", "SMMA (RMA)", "WMA", "VWMA"])
ma6_source = input(close  , ""     , inline="MA #6")
ma6_length = input.int(30    , ""     , inline="MA #6", minval=1)

show_ma7   = input(true   , "MA №7", inline="MA #7")
ma7_type   = input.string("EMA"  , ""     , inline="MA #7", options=["SMA", "EMA", "SMMA (RMA)", "WMA", "VWMA"])
ma7_source = input(close  , ""     , inline="MA #7")
ma7_length = input.int(45    , ""     , inline="MA #7", minval=1)

show_ma8   = input(true   , "MA №8", inline="MA #8")
ma8_type   = input.string("EMA"  , ""     , inline="MA #8", options=["SMA", "EMA", "SMMA (RMA)", "WMA", "VWMA"])
ma8_source = input(close  , ""     , inline="MA #8")
ma8_length = input.int(50    , ""     , inline="MA #8", minval=1)

show_ma9   = input(true   , "200MA", inline="200MA")
ma9_type   = input.string("EMA"  , ""     , inline="200MA", options=["SMA", "EMA", "SMMA (RMA)", "WMA", "VWMA"])
ma9_source = input(close  , ""     , inline="200MA")
ma9_color = input(#FFFF00, ""     , inline="200MA")
ma9_length = 200

// PLOTS
ma1 = ma(ma1_source, ma1_length, ma1_type)
ma2 = ma(ma2_source, ma2_length, ma2_type)
ma3 = ma(ma3_source, ma3_length, ma3_type)
ma4 = ma(ma4_source, ma4_length, ma4_type)
ma5 = ma(ma5_source, ma5_length, ma5_type)
ma6 = ma(ma6_source, ma6_length, ma6_type)
ma7 = ma(ma7_source, ma7_length, ma7_type)
ma8 = ma(ma8_source, ma8_length, ma8_type)
ma9 = ma(ma9_source, ma9_length, ma9_type)

ma1_color  = ma1>ma2 ? color.green : color.red
ma2_color  = ma2>ma3 ? color.green : color.red
ma3_color  = ma3>ma4 ? color.green : color.red
ma4_color  = ma4>ma5 ? color.green : color.red
ma5_color  = ma5>ma6 ? color.green : color.red
ma6_color  = ma6>ma7 ? color.green : color.red
ma7_color  = ma7>ma8 ? color.green : color.red
ma8_color  = ma7>ma8 ? color.green : color.red

plot(show_ma1 ? ma1 : na, color = color.new(ma1_color,0), title="MA №1", linewidth=2)
plot(show_ma2 ? ma2 : na, color = color.new(ma2_color,10), title="MA №2", linewidth=2)
plot(show_ma3 ? ma3 : na, color = color.new(ma3_color,20), title="MA №3", linewidth=2)
plot(show_ma4 ? ma4 : na, color = color.new(ma4_color,30), title="MA №4", linewidth=2)
plot(show_ma5 ? ma5 : na, color = color.new(ma5_color,40), title="MA №5", linewidth=2)
plot(show_ma6 ? ma6 : na, color = color.new(ma6_color,50), title="MA №6", linewidth=2)
plot(show_ma7 ? ma7 : na, color = color.new(ma7_color,60), title="MA №7", linewidth=2)
plot(show_ma8 ? ma8 : na, color = color.new(ma8_color,70), title="MA №8", linewidth=2)
plot(show_ma9 ? ma9 : na, color = color.new(ma9_color,0), title="MA №9", linewidth=2)